name: Update Colors

on:
  schedule:
    - cron: '10 10 */3 * *'

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: update
        run: |
          yarn install
          yarn run update
      - name: Commit files
        run: |
          git config --local user.email "minojiro@users.noreply.github.com"
          git config --local user.name "minojiro"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add colors.json
            git commit -m "update colors" -a
            npm version patch
            git push origin HEAD:${GITHUB_REF}
            git push --tags
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
