name: Update Colors

on:
  workflow_dispatch:
  schedule:
    - cron: "10 10 */3 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    environment:
      name: prod
    timeout-minutes: 2
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
          scope: "gh-lang-colors"
      - name: update
        run: node update.js
      - name: Commit files
        run: |
          git config --local user.email "minojiro@users.noreply.github.com"
          git config --local user.name "minojiro"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add colors.json
            git commit -m "update colors"
            npm version $(node -e "const v=require('child_process').execSync('npm view gh-lang-colors version').toString().trim().split('.'); v[2]++; console.log(v.join('.'))")
            git push origin HEAD:${GITHUB_REF}
            git push --tags
            npm publish --access=public --provenance
          else
            echo "差分がありません"
          fi
