name: Update Colors

on: [push]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run update
      - name: git setting
        run: |
          git config --local user.email "minojiro@users.noreply.github.com"
          git config --local user.name "minojiro"
      - name: Commit files
        run: |
          git add colors.json
          git commit -m "update colors" -a
          git pull
          git push origin master
